FROM centos:7
LABEL Author = "Khan"
LABEL organization  = "DEVOPS"
RUN yum update -y && yum install httpd -y
ENTRYPOINT [ "echo" ]
CMD [ "Hello-World" ]
#CMD ["echo", "hello-world"]

#https://github.com/GitRepositoryPrac/DockerPracandNotes/tree/master
#https://github.com/GitRepositoryPrac/DockerPracandNotes.git
#https://github.com/GitRepositoryPrac/DockerPracandNotes.git
#https://github.com/GitRepositoryPrac/DockerPracandNotes.git
#https://github.com/GitRepositoryPrac/DockerPracandNotes.git